### ISSUE TITLE
[Suggestion]: TAB for money

### ISSUE THREAD

**Issue by westor7** [jason0611/FS22_ExtendedTabbing#12]
Hello,

It would be nice to see spending some amount of money when using the TAB to teleport in the next vehicle, depending with the distance to spend an X amount. also an option in settings to change the base amount.

- Thanks!

**Comment by jason0611** [comment]
Hi westor7,

I'm sorry, but intention of Extended Tabbing was the ability to switch quickly between vehicles nearby, plus the option to directly jump into up to five defined vehicles. The goal is to simplify the game, especially for the single player.
Generating costs would be a deep intervention in the script which I do not want to do.

Regards,
Martin
